# Generated by Django 3.2 on 2022-04-10 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.DecimalField(choices=[(1, ' ⭐ '), (2, ' ⭐  ⭐ '), (3, ' ⭐  ⭐  ⭐ '), (4, ' ⭐  ⭐  ⭐  ⭐ '), (5, ' ⭐  ⭐  ⭐  ⭐  ⭐ ')], decimal_places=0, max_digits=2, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
