# Generated by Django 3.2 on 2022-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
